languageCode = "en-us"
title = "Jonathan Keane Photography"
# Supposedly: if specified, it messes up some links on the preview site, is it needed at all?
baseURL = "https://photo.jonkeane.com"
theme = "hugo-theme-massively-jtk"
googleanalytics = "G-CPQDC0642Z"
# disableKinds = ["taxonomy", "taxonomyTerm", "section"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
timeout = 600

sectionPagesMenu = "main"

[[menu.main]]
   identifier="intro"
   name = "Intro"
   url  = "/"
   weight = 1

[[menu.main]]
   identifier="gallery"
   name = "gallery"
   url  = "/gallery/"
   weight = 2

[[menu.main]]
   identifier="prints"
   name = "prints"
   url  = "/prints/"
   weight = 3

[[menu.main]]
   identifier="about"
   name = "about"
   url  = "/about/"
   weight = 4

[params]
  description = "Travelling the world and taking photographs of things that catch my eye. Landscapes, cityscapes, nature, people."
  images = ["photo-jonkeane.jpg"]
  title = "Jonathan Keane Photography"
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  dateFormat = "2006-01-02"

[taxonomies]
  series = "series"

[params.nanog]
  flickr_userid = "65556368@N00"
  # flickr_userid = "jonkeane"
  tagBlockList = "nogallery"

[params.slider]
    enable = true

[params.meta]
   keywords = "photography, photographs, photos, prints, art, framed prints, travel, landscapes, cityscapes, nature, japan, chicago, australia"
   description = "Travelling the world and taking photographs of things that catch my eye. Landscapes, cityscapes, nature, people."
   robots = "index, follow, noarchive"
   googlebot = "noarchive"
   googlesiteverification = "f2zJ8lbq0tyR9J_pME6DbTDQWFrLLH-m98SKSbgnmCE"

[imaging.exif]
  includeFields = "Description"

[params.posts]
  featuredPost = false
  pageSize = "10"

# Below parameters can be set to override default post settings
# [params.posts]
#   featuredPost = false
#     folderName = "post"
#     pageSize = "6"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
