languageCode = "en-us"
title = "Jonathan Keane Photography"
# baseURL = "http://photo.jonkeane.com/"
theme = "hugo-theme-massively-jtk"
googleanalytics = "UA-147422220-1"
# disableKinds = ["taxonomy", "taxonomyTerm", "section"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

sectionPagesMenu = "main"

[[menu.main]]
   identifier="intro"
   name = "Intro"
   url  = "/"
   weight = 1

[[menu.main]]
   identifier="store"
   name = "store"
   url  = "/store/"
   weight = 2

[[menu.main]]
   identifier="gallery"
   name = "gallery"
   url  = "/gallery/"
   weight = 3

[[menu.main]]
   identifier="about"
   name = "about"
   url  = "/about/"
   weight = 4

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

[params.nanog]
  # flickr_userid = "65556368@N00"
  flickr_userid = "jonkeane"
  thumbnailHoverEffect2 = "imageScaleIn80|labelSlideUp|label_backgroundColor_rgba(50,50,50,0.01)_rgba(50,50,50,0.8)"
  tagBlackList = "nogallery"

[params.slider]
    enable = true

[params.meta]
   keywords = "photography, photographs, photos, prints, art, framed prints, travel, landscapes, cityscapes, nature, japan, chicago, australia"
   description = "Jonathan Keane Photography — Travelling the world and taking photographs of things that catch my eye. Landscapes, cityscapes, nature, people."
   robots = "index, follow, noarchive"
   googlebot = "noarchive"
   googlesiteverification = "f2zJ8lbq0tyR9J_pME6DbTDQWFrLLH-m98SKSbgnmCE"

[imaging.exif]
  includeFields = "Description"

# Below parameters can be set to override default post settings
# [params.posts]
#   featuredPost = false
#     folderName = "post"
#     pageSize = "6"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
