languageCode = "en-us"
title = "Jonathan Keane Photography"
# baseURL = "http://photo.jonkeane.com/"
theme = "hugo-theme-massively-jtk"
googleanalytics = "UA-147422220-1"
# disableKinds = ["taxonomy", "taxonomyTerm", "section"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


sectionPagesMenu = "main"

[[menu.main]]
   identifier="intro"
   name = "Intro"
   url  = "/"
   weight = 1

[[menu.main]]
   identifier="store"
   name = "store"
   url  = "/store/"
   weight = 2

[[menu.main]]
   identifier="gallery"
   name = "gallery"
   url  = "/gallery/"
   weight = 3


# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

[params.slider]
    enable = true

[imaging.exif]
  includeFields = ".*"


# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
